# Generated by Django 5.0.7 on 2024-08-07 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_student_email_remove_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
        migrations.AddField(
            model_name='project',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Proposed', 'Proposed'), ('Available', 'Available'), ('Requested', 'Requested'), ('Confirmed', 'Confirmed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.supervisor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
