# Generated by Django 5.0.7 on 2024-08-09 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_project_student_project_proposed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='null@sussex.com', max_length=30, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(default='surname', max_length=30, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(default='null@sussex.com', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='name',
            field=models.CharField(default='name', max_length=30, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='surname',
            field=models.CharField(default='surname', max_length=30, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
